### ISSUE TITLE
How can we get submit.csv?

### ISSUE THREAD

**Issue by YOONHO-CHOI** [walsh-quail-labs/Cell-Segmentation#1]
Hi, I am currently running your cell segmentation code with my data.
Within the code 'demo.m', the submit.csv file is required but I couldn't find it.
What is the exact role of submit.csv and how can I get it?
Thank you.

**Comment by YOONHO-CHOI** [comment]
I solved

**Comment by jgu13** [comment]
The program saves submit.csv in the MaskRCNN python scripts. [Here](https://github.com/walsh-quail-labs/Cell-Segmentation/blob/main/Lib/MaskRCNN/samples/nucleus/find_nucleus.py) in line 405.
